name: Deploy RC to Staging

on:
  pull_request:
    branches:
      - master
      - "release-[0-9]+.[0-9]+.x"

jobs:
  deploy_test_staging:
    name: Deploy Test Staging
    runs-on: ubuntu-latest
    outputs:
      hasDiff: ${{ steps.check_diff.outputs.hasDiff }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get Name Image & Tag From Event Data
        id: get_deploy_info
        run: |
          . .github/workflows/get_deploy_info_from_PR_body.sh '${{ github.event.pull_request.body }}'

      - name: Check Diff In Stack File
        id: check_diff
        run: |
          diff=$(git diff origin/master HEAD stack.yml)
          if [ -z "$diff" ]; then
            echo "##[set-output name=hasDiff;]false"
          else
            echo "##[set-output name=hasDiff;]true"
          fi

      - name: Log Outputs
        run: |
          echo "Has Diff? ${{ steps.check_diff.outputs.hasDiff }}"
          echo "Service to Change: ${{ steps.get_deploy_info.outputs.serviceName }}"
          echo "With Image: ${{ steps.get_deploy_info.outputs.image }}"
          echo "With Tag: ${{ steps.get_deploy_info.outputs.tag }}"

      - name: Conditionally fail
        if: github.event.label.name == 'fail'
        run: exit 1